### ISSUE TITLE
Building for Windows (Needs some fix, See comments below)

### ISSUE THREAD

**Issue by GalaxianMonster** [Gen-lang/Gen#14]
The issue is there are no builds for Windows.
You can do that with simply this:
```
pip install pyinstaller
pyinstaller ./main.py --onefile
COPY ./dist/main.exe ./pygen.exe
```
Python's CLI is the same as Python Linux build CLI.
Pyinstaller needs to be in windows in order to build it to .EXE file.
So it's up to you now on how to build it on windows while on Linux.
You need to add it on PATH environment variable though if you want to access with only "pygen" and not the whole path to the application, which I don't know how.

I'm not an expert on Windows so I might be wrong.

(Nice programming language btw)

**Comment by bichanna** [comment]
Thanks! Could you contribute? :D

**Comment by bichanna** [comment]
I know almost nothing about Windows. So, if you can, please contribute as best as you can.

**Comment by GalaxianMonster** [comment]
Sorry for not replying. I might be able to contribute.

**Comment by GalaxianMonster** [comment]
PR: #15

**Comment by GalaxianMonster** [comment]
Hi, recently I found out that the syntax of the COPY command has some syntax error.
I'm really sorry.

Here is the updated command:
```
@pip install pyinstaller
@pyinstaller ./main.py --onefile
@COPY ".\dist\main.exe" ".\gen.exe"
# Set environment variable here
@echo "PyGen compilation Succeeded"
@echo "Type 'gen'"
```
I don't have time to submit a PR so it's up to you to edit the existing windows build cmd in the Makefile.

**Comment by GalaxianMonster** [comment]
I found it out by testing pygen on windows.

**Comment by bichanna** [comment]
Thanks!

**Comment by GalaxianMonster** [comment]
Whats the problem?
