### ISSUE TITLE
Library readline not available for Windows

### ISSUE THREAD

**Issue by GalaxianMonster** [Gen-lang/Gen#16]
So I tested pygen on Windows.
I needed to install readline in order to make gen.exe work.
When installing readline on Windows using:
```
pip install readline
```
It does not work.
One of the errors:
```
error: this module is not meant to work on Windows
```
That's all.

**Comment by bichanna** [comment]
Hmm. I don't know how to solve this

**Comment by GalaxianMonster** [comment]
I don't know either.

**Comment by bichanna** [comment]
@GalaxianMonster Try importing `pyreadline` library.

**Comment by GalaxianMonster** [comment]
Ok.

**Comment by GalaxianMonster** [comment]
Why do you need readline though?

**Comment by GalaxianMonster** [comment]
I don't see readline used in any code.

**Comment by bichanna** [comment]
Sorry, I don't have much time today. But basically, without `readline`, you can't use arrows when using the REPL.

**Comment by GalaxianMonster** [comment]
Hmm I see. Ok.
