### ISSUE TITLE
Gen not handling exceptions from Python

### ISSUE THREAD

**Issue by GalaxianMonster** [Gen-lang/Gen#17]
Gen not able to handle exceptions like KeyboardInterrupt(coming from Python).
Here is a screenshot:
![image](https://user-images.githubusercontent.com/72903778/150314532-52443697-1048-422f-ab64-744d1b101305.png)

**Comment by bichanna** [comment]
I'm pretty busy, so could you fix that?

**Comment by GalaxianMonster** [comment]
Ummmm. I don't know how to handle exceptions in Python..

**Comment by bichanna** [comment]
I just solved it. See this commit: https://github.com/Gen-lang/Gen/commit/a5a0e6a510fb3196d09bda7dc4179ee393fd03eb !
