### ISSUE TITLE
Gen "InvalidSyntaxError" pointing on an empty character

### ISSUE THREAD

**Issue by GalaxianMonster** [Gen-lang/Gen#18]
Here is a screenshot:
![image](https://user-images.githubusercontent.com/72903778/150318593-b41a97ab-3cbe-4969-964d-cda3608346d7.png)

Command used:
```
gen main.gen
```

main.gen:
![image](https://user-images.githubusercontent.com/72903778/150318800-679a3619-f16b-4050-b3b7-35f66061e9c8.png)

**Comment by bichanna** [comment]
I'll look at the string_with_arrows function.

**Comment by bichanna** [comment]
Gen checks syntax first and then checks for undefined vars (in this case, `endmak`). So, when Gen throws this error, it does not know `endmak` is undefined yet.

**Comment by GalaxianMonster** [comment]
Oh thanks.
