### ISSUE TITLE
Gen not producing error with an invalid one line for loop

### ISSUE THREAD

**Issue by GalaxianMonster** [Gen-lang/Gen#19]
Screenshot:
![image](https://user-images.githubusercontent.com/72903778/150319224-20da7432-8489-4003-9361-67285b744ab4.png)

Code used:
```
for i = 1 through 1 then i=i endllllllll
```

**Comment by bichanna** [comment]
It is not an error. One line for loop does not need `end` at the end.

**Comment by GalaxianMonster** [comment]
Thanks for clarifying.
