### ISSUE TITLE
Gen BinOpNode object has no attribute 'var_name_token'

### ISSUE THREAD

**Issue by GalaxianMonster** [Gen-lang/Gen#20]
Screenshot:
![image](https://user-images.githubusercontent.com/72903778/150327028-276023f9-f988-48f5-8779-e30e1004c706.png)

Variable "i":
```
i = [[[]]]
```

**Comment by bichanna** [comment]
Thanks!

**Comment by bichanna** [comment]
Actually, map is not working yet even though I said so in a commit.

**Comment by bichanna** [comment]
* map and array.

**Comment by GalaxianMonster** [comment]
Thanks for clarifying.
