### ISSUE TITLE
If statement does not work with complicated variable access

### ISSUE THREAD

**Issue by bichanna** [Gen-lang/Gen#21]
This if statement does not work:
```
if arr@i == arr@j then # do_something
```

So, to solve this, just assign them to new variables for now:
```
a = arr@i
b = arr@j
if a == b then # do_something
```

*Update*
See the [comment](https://github.com/Gen-lang/Gen/issues/21#issuecomment-1019364610) below, which is way better.

**Comment by bichanna** [comment]
Actually, this problem can be solved without creating disposable variables:
```
if (arr@i) == (arr@j) then # do something
```

**Comment by GalaxianMonster** [comment]
Umm, will you fix this issue so that you don't need to add parenthesis or create disposable variables?

**Comment by bichanna** [comment]
I'm trying to solve this, but it might take some time.
