### ISSUE TITLE
Suggestions for the import feature

### ISSUE THREAD

**Issue by GalaxianMonster** [Gen-lang/Gen#24]
# My suggestions for the import feature: 
- Make it a function like:
```
import("library file")
```
or just a keyword:
```
import "library file"
```
- Make import return a map of the library
- "library file" should be the path to the file

That's all :)))

**Comment by bichanna** [comment]
What do you mean by returning a map of the library?

**Comment by GalaxianMonster** [comment]
I mean that:
```
lib = import("example.gen")
lib@function()
```

**Comment by GalaxianMonster** [comment]
Pretty much the same with lua.

**Comment by bichanna** [comment]
I don't know how to handle the `.`...

**Comment by GalaxianMonster** [comment]
Oof mistake

**Comment by GalaxianMonster** [comment]
Edited code

**Comment by bichanna** [comment]
I'll try to implement that.

**Comment by GalaxianMonster** [comment]
Ok. thanks.

**Comment by bichanna** [comment]
I did it.

**Comment by GalaxianMonster** [comment]
Nice.
