### ISSUE TITLE
Is it time to release 0.2.0?

### ISSUE THREAD

**Issue by bichanna** [Gen-lang/Gen#25]
I think map and array are quite stable now, and I implemented importing. So, I think it's time to release the 0.2.0 version.

What do you think?

**Comment by bichanna** [comment]
Or since I added the `import` built-in func, maybe I should create a standard library.

**Comment by GalaxianMonster** [comment]
Yes. both.

**Comment by GalaxianMonster** [comment]
release 0.2.0
