### ISSUE TITLE
Need help on creating a web-based playground

### ISSUE THREAD

**Issue by bichanna** [Gen-lang/Gen#28]
I've never built a web-based playground.
Could you guys help me create one?

**Comment by GalaxianMonster** [comment]
Umm. I think you can send an http request to execute the program in a sandboxed environment and return the output or errors. Or maybe just reimplement it in javascript, typescript or wasm.

**Comment by bichanna** [comment]
Or maybe just copy the whole source code and pass the entire text written in the playground to the Gen interpreter.

**Comment by GalaxianMonster** [comment]
How would you run a python file on the web browser?
