### ISSUE TITLE
About the import function

### ISSUE THREAD

**Issue by bichanna** [Gen-lang/Gen#29]
Currently, this is how to use the import function:
```
import("examples/bubble_sort.gen")

arr = bubble_sort([12, 43, 23, 44])
println(arr)
```

But would you prefer something like this?
```
imported = import("examples/bubble_sort.gen")

arr = (imported@"bubble_sort")([12, 43, 23, 44])
# or if possible, I may make it like this:
# arr = imported@bubble_sort([12, 43, 23, 44])
println(arr)
```

I'm still experimenting with the latter.

**Comment by GalaxianMonster** [comment]
Maybe both, when not assigned to a variable, it would add variable with file name. If assigned to variable, it would add variable with the variable name specified by the variable assignment.

**Comment by bichanna** [comment]
Hmm. I don't like assigning to a variable implicitly. So, it would add a variable with the content of the import.

**Comment by GalaxianMonster** [comment]
Umm ok.
