### ISSUE TITLE
Iterate an array

### ISSUE THREAD

**Issue by bichanna** [Gen-lang/Gen#31]
I just wanted to ask you guys if creating another loop just for arrays:
```
iterate arr as i then
    println(i)
end
```

Or should I just create the `in` keyword?
```
for i in arr then
    println(i)
end
```

**Comment by GalaxianMonster** [comment]
Maybe create an in keyword.

**Comment by bichanna** [comment]
I think I will.

**Comment by bichanna** [comment]
I succeeded in making the in keyword available!

**Comment by GalaxianMonster** [comment]
nice
